---
title: "Replication"
author: "Yana Otlan and Frank Wyer"
date: "December, 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Load Packages
library(readr)
library(foreign)
library(sandwich)
library(lmtest)
library(rdrobust)
library(AER)
library(rdd)
library(ggplot2)
library(broom)
library(clubSandwich)
library(texreg)
```

```{r}
#Read in replication data
dta_mid <- read.dta('/Users/frankwyer/Desktop/Fall 17/Maximum Likelihood/Replication Project/Yana/HorowitzStamLeadersIOMIDReplication.dta')
dta_war <- read.dta('/Users/frankwyer/Desktop/Fall 17/Maximum Likelihood/Replication Project/Yana/HorowitzStamLeadersIOWarReplication.dta')
```

```{r}
#Define Luke's ClusterRSE to replicate Stata's clustered standard errors

clusterRSE <- function(fm, clusterName, df, correction = 'fancy'){
  
  library(sandwich)
  library(lmtest)
  
  ## Get variable names
  vars <- all.vars(formula(fm)[[3]])
  ## Get the model.matrix
  modelMatrix <- df[complete.cases(df[, c(vars)]), c(vars, clusterName)]
  
  ## Extract all of the clusters
  cl <- modelMatrix[,clusterName]
  ## Number of clusters
  m <- length(unique(cl))
  ## Number of covariates (minus the column of cluster IDs but plus one for constant)
  p <- ncol(modelMatrix)
  ## Number of observations 
  n <- nrow(modelMatrix)

  ## Set the finite sample correction
  if (correction == 'fancy') {
    dfc <- (m / (m - 1)) * ((n - 1) / (n - p))
  } else if (correction == 'simple') {
    dfc <- (m / (m - 1))
  } else if (correction == 'none') {
    dfc <- 1
  } else {
    print("Improper correction. Default 'fancy' was used.")
    print("Please choose correction 'fancy', 'simple', or 'none'")
    dfc <- (m / (m - 1)) * ((n - 1) / (n - p))
  }
  
  ## Compute the meat
  uj  <- apply(estfun(fm), 2, function(x) tapply(x, cl, sum))
  ## Finalize the cluster robust variance-covariance matrix
  vcovCL <- dfc*sandwich(fm, meat=crossprod(uj)/n)

  print(dfc)
    
  out = list()
  out$model <- fm
  out$vcovCL <- vcovCL
  out$coeftest <- coeftest(fm, vcovCL)
  return(out)
}
```


#Run the models as they are in the paper

```{r}
#Fit model 1

model1 <- glm(cwinit ~ milnoncombat + combat + rebel + warwin + warloss + rebelwin + 
                rebelloss + age + aut + cinc + tau_lead + officetenure1000 + 
                fiveyearchallengelag + cwpceyrs1 + cwpceyrs2 + cwpceyrs3, data =
                dta_mid, family=binomial(link="logit"))

#Cluster SEs and print results
m1_CR <- clusterRSE(model1, "leaderid", dta_mid, correction = 'fancy')
m1_result <- round(m1_CR$coeftest, 4)
```


#model 2

```{r}
#fit model 2
model2 <- glm(initiation ~ milnoncombat + combat + rebel + warwin + warloss + rebelwin
              + rebelloss + age + aut + cinc + tau_lead + officetenure1000 +
                fiveyearchallengelag + cwpceyrs1 + cwpceyrs2 + cwpceyrs3, data =
                na.omit(dta_war), family=binomial(link="logit"))

round(coeftest(model2), 3)

m2_CR <- clusterRSE(model2, "leaderid", na.omit(dta_war), correction = 'fancy')
m2_result <- round(m2_CR$coeftest, 4)

```


#model 3

```{r}
#fit model 3: Polity Interaction
model3 <- glm(cwinit ~ milnoncombat + combat + rebel + milpolity + combatpolity +
                rebelpolity + milrebel + combatrebel + warwin + warloss + rebelwin +
                rebelloss + age + polity21 + cinc + tau_lead + officetenure1000 +
                fiveyearchallengelag + cwpceyrs1 + cwpceyrs2 + cwpceyrs3, data =
                dta_mid, family=binomial(link="logit")) 

m3_CR <- clusterRSE(model3, "leaderid", dta_mid, correction = 'fancy')
m3_result <- round(m3_CR$coeftest, 4)

```

#Model 4
```{r}
#model 4: Autocracy Interaction
model4 <- glm(cwinit ~ milnoncombat + combat + rebel + milaut + combataut + rebelaut +
                milrebel + combatrebel + warwin + warloss + rebelwin + rebelloss + age
              + aut +  cinc + tau_lead + officetenure1000 + fiveyearchallengelag +
                cwpceyrs1 + cwpceyrs2 + cwpceyrs3, data = dta_mid,
              family=binomial(link="logit")) 

m4_CR <- clusterRSE(model4, "leaderid", dta_mid, correction = 'fancy')
m4_result <- round(m4_CR$coeftest, 4)


```

#Model 5
```{r}
#model 5: MID interaction with Military Regime 

#filter data to between 1945 and 2000
new_dta_mid <- dta_mid %>% 
  filter(year > 1945 & year <2000)
 
model5 <- glm(cwinit ~ milnoncombat + combat + rebel + milmil + combatmil + rebelmil +
                milrebel + combatrebel + warwin + warloss + rebelwin + rebelloss + age
              + cinc + cgvmildict + tau_lead + officetenure1000 + fiveyearchallengelag
              + cwpceyrs1 + cwpceyrs2 + cwpceyrs3, data = new_dta_mid,
              family=binomial(link="logit")) 

m5_CR <- clusterRSE(model5, "leaderid", new_dta_mid, correction = 'fancy')
m5_result <- round(m5_CR$coeftest, 4)

```


```{r}
#create table

texreg(l = list(m1_result, m2_result, m3_result, m4_result, m5_result), stars = c(0.01, 0.05, 0.1), digits = 3)

```

#Part 2: Robustness

#Model 6
```{r}
#Model 6: Leaders randomly selected into office via leader death

model6 <- glm(cwinit ~ milnoncombat + combat + rebel + warwin + warloss + rebelwin +
                rebelloss + age + cinc + aut + tau_lead + officetenure1000 +
                fiveyearchallengelag + cwpceyrs1 + cwpceyrs2 + cwpceyrs3, data =
                dta_mid %>% filter(treatment==1 & regular==1),
                                   family=binomial(link="logit"))

m6_CR <- clusterRSE(model6, "leaderid", dta_mid %>% filter(treatment==1 & regular==1),
                    correction = 'fancy')
m6_result <- round(m6_CR$coeftest, 4)
```


#Model 7
```{r}
#Model 7: Polity Interaction
model7 <- glm(cwinit ~ milnoncombat + combat + rebel + milpolity + combatpolity +
                rebelpolity + milrebel + combatrebel + warwin + warloss + rebelwin +
                rebelloss + age + polity21 + cinc + tau_lead + officetenure1000 +
                cwpceyrs1 + cwpceyrs2 + cwpceyrs3, data = dta_mid %>%
                filter(fiveyearchallengelag==0), family=binomial(link="logit"))

m7_CR <- clusterRSE(model7, "leaderid", dta_mid %>% filter(fiveyearchallengelag==0),
                    correction = 'fancy')
m7_result <- round(m7_CR$coeftest, 4)
```

#Model 8
```{r}
#Model 8: Autocracy Interaction
model8 <- glm(cwinit ~ milnoncombat + combat + rebel + milaut + combataut + rebelaut +
                milrebel + combatrebel + warwin + warloss + rebelwin + rebelloss + age
              + aut + cinc + tau_lead + officetenure1000 + cwpceyrs1 + cwpceyrs2 +
                cwpceyrs3, data = dta_mid %>% filter(fiveyearchallengelag==0),
              family=binomial(link="logit"))

m8_CR <- clusterRSE(model8, "leaderid", dta_mid %>% filter(fiveyearchallengelag==0),
                    correction = 'fancy')

m8_result <- round(m8_CR$coeftest, 4)
```


#Model 9

```{r}
#Model 9: Military Interaction
model9 <- glm(cwinit ~ milnoncombat + combat + rebel + milmil + combatmil + rebelmil + milrebel + combatrebel + warwin + warloss + rebelwin + rebelloss + age + cinc + cgvmildict + tau_lead + officetenure1000 + cwpceyrs1 + cwpceyrs2 + cwpceyrs3, data = dta_mid %>% filter(year > 1945 & year <2000 & fiveyearchallengelag==0), family=binomial(link="logit"))

m9_CR <- clusterRSE(model9, "leaderid", dta_mid %>% filter(year > 1945 & year <2000 &
                fiveyearchallengelag==0), correction = 'fancy')

m9_result <- round(m9_CR$coeftest, 4)
```

```{r}
#create table for models 6-9

texreg(l = list(m6_result, m7_result, m8_result, m9_result), stars = c(0.01, 0.05, 0.1), digits = 3)

```


